spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: com.mysql.jdbc.Driver
  redis:
    port: 6379

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
    username: me
    password: meme
  redis:
    host: localhost

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://database:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  redis:
    host: redis
